# Generated by Django 4.1.2 on 2024-11-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='steps',
            field=models.ManyToManyField(to='users.lesson'),
        ),
    ]
